# Generated by Django 4.2.6 on 2023-11-15 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_alter_review_ticket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("-time_created",)},
        ),
    ]
